### ISSUE TITLE
speexdsp required in code for Peak Detection options but not pulled in by cmake?

### ISSUE THREAD

**Issue by gibbon-joel** [jiixyj/loudness-scanner#21]
I noticed that libspeexdsp seems to be required (scanner/scanner.c:70) for peak detection options in the scanner but the CMake Infrastructure seems to not pull it in in any way. Is this intentional?

**Comment by jiixyj** [comment]
You are right! I forgot to remove those ifdefs. I've just committed a fix.

**Comment by gibbon-joel** [comment]
Thank you very much :) Issue solved.
