### ISSUE TITLE
Peak analysis on MP3s yields sample peaks >1

### ISSUE THREAD

**Issue by gibbon-joel** [jiixyj/loudness-scanner#22]
Hi,

Having an mp3 file test.mp3 and a derived wav file (created from the mp3 using mpg123 -w) I get the following results:

    root@utena:~# /usr/src/joel/loudness-scanner/build/loudness scan -l -p all test.*
      Loudness,     LRA, Sample peak,   True peak,  True peak                      
     -8.5 LUFS,  3.8 LU,    1.376949,    1.714404,   4.7 dBTP, test.mp3
     -8.5 LUFS,  3.8 LU,    1.000000,    1.652230,   4.4 dBTP, test.wav
    -------------------------------------------------------------------------------
     -8.5 LUFS,  3.8 LU,    1.376949,    1.714404,   4.7 dBTP

The 1.0000 output is expected in a normalized file, but a sample peak >1 should not be representable. How can that happen?

Current git code (7eb4e9506d2d2ca68869aadd785c41834ac2e4f5)
    -- status          found / disabled --
    -- queue.h:        yes     using system copy of queue.h
    -- glib-2.0:       yes     no
    -- gthread-2.0:    yes     no    
    -- sndfile:        yes     no
    -- taglib:         yes     no
    -- mpg123:         yes     no
    -- mpcdec:         yes     no
    -- gstreamer:      no      no
    -- ffmpeg:         yes     yes
    -- rsvg2:          no      no
    -- gtk2:           yes     no
    -- qt4:            yes     no
    -- qt5:            no      no

so I am probably using the mpg123 plugin. I can provide both files though there might be copyright implications.

**Comment by jiixyj** [comment]
This is so called "decoder clipping" or "output clipping". A mp3 decoder outputs floating point samples that may have a value that is >1.0 (due to the lossy nature of mp3). For conversion to .wav the output is clipped to 1.0.
See also http://wiki.hydrogenaud.io/index.php?title=ReplayGain_1.0_specification#Peak_amplitude:

> Psychoacoustically coded audio, such as MP3, does not exist as a sequence of samples until it is decoded. Psychoacoustic coding of a heavily limited file can lead to sample values larger than digital full scale upon decoding. The coded files must be decoded using a fully compliant decoder that allows peak overflows (i.e. has headroom) and may result in peak amplitude values greater than 1.0.

**Comment by gibbon-joel** [comment]
ok... that makes it easier to understand why the True Peak of the clipped WAV is so similar to the decoded MP3. Even better... so this really is a feature - and another demonstration that lossy audio compression has strange side effects.

**Comment by gibbon-joel** [comment]
Thank you for the fast and precise explanation. This can be closed I guess.
