### ISSUE TITLE
Compile to windows

### ISSUE THREAD

**Issue by mrbichel** [jiixyj/loudness-scanner#23]
I am having trouble compiling to windows. 

I attempted both using visual studio on windows and through mingw32. But I am not sure which is the right way to go. I have been developing on os x where everything compiles nicely. 

Should I attempt to cross compile or is it easier to compile it with cmake / visual studio / code blocks on windows? 

I am a bit lost in the process, any pointers would be helpful.

Currently I'm getting stuck at #include <sys/queue.h> not being available on windows when trying through visual studio.

**Comment by jiixyj** [comment]
Building with msys2 (https://msys2.github.io/) is probably the easiest way.
You have to run cmake like this (in the mingw64 environment) so that it finds the queue.h header and uses the right makefile generator:

    cmake .. -G "Unix Makefiles" -DENABLE_INTERNAL_QUEUE_H=ON

I've installed the following packages to get loudness.exe to build:

```
pacman -S cmake git
pacman -S mingw64/mingw-w64-x86_64-libsndfile
pacman -S mingw64/mingw-w64-x86_64-cmake
pacman -S mingw64/mingw-w64-x86_64-mpg123
pacman -S mingw64/mingw-w64-x86_64-ffmpeg
pacman -S mingw64/mingw-w64-x86_64-gcc
pacman -S mingw64/mingw-w64-x86_64-taglib
pacman -S mingw-w64-x86_64-toolchain
pacman -S base-devel
```

**Comment by mrbichel** [comment]
Thanks. I successfully compiled the static libs. But how do I instruct cmake to output the loudness .exe. I ran install also but it only creates .dll and .a files for libebur128.

**Comment by jiixyj** [comment]
Currently there are no install targets for loudness.exe. But loudness.exe should have been built in the build folder... Maybe there is a library still missing, for example glib2? You can search for libraries to install with "pacman -Ss glib".
Just running "cmake .." should give you an overview of all needed libraries and if they were found or not:

```
-- status          found / disabled --
-- queue.h:        yes     using system copy of queue.h
-- glib-2.0:       yes     no
-- gthread-2.0:    yes     no
-- sndfile:        yes     no
-- taglib:         yes     no
-- mpg123:         yes     no
-- mpcdec:         no      no
-- gstreamer:      yes     no
-- ffmpeg:         yes     no
-- rsvg2:          yes     no
-- gtk2:           yes     no
-- qt4:            yes     no
-- qt5:            yes     no
```

**Comment by mrbichel** [comment]
Ah my problem was with cmake cache files. Deleted my build folder, restarted msys2 and ran cmake again then it worked. Thanks a lot.

**Comment by sergeevabc** [comment]
Could someone be so kind to share a binary for Windows 7 x64? You can compress it into ZIP and attach it right here.

**Comment by avengerx** [comment]
I'm trying to make a github workflow to build this from github itself. Lucky me, the workflows interface broke right when I was going to test the run. I will post later and maybe make a pull request with the workflow making windows (and maybe linux) builds that could be attached to the releases. Or in the least one could fork the repository and run the workflow in order to build without the need to set up a build environment home.

**Comment by flawrist** [comment]
Err… Hello?
