### ISSUE TITLE
Tagging behavior of Opus files changed – R128_TRACK_GAIN and R128_ALBUM_GAIN not set anymore

### ISSUE THREAD

**Issue by l3u** [jiixyj/loudness-scanner#40]
Hi all :-)

I'm not quite sure what caused this, but the result of tagging Opus files has changed.

Some time ago, I tagged a lot of Opus files. For each file, a `R128_TRACK_GAIN` and `R128_ALBUM_GAIN` was added. Viewing such a file with opusinfo would e.g. yield:

    New logical stream (#1, serial: 3e5b8b24): type opus
    Encoded with libopus 1.3.1, libopusenc 0.2.1
    User comments section follows...
            ...
            R128_TRACK_GAIN=-3354
            R128_ALBUM_GAIN=-3405
            ...
    Opus stream 1:
            ...
            Playback gain: 0 dB
            ...
    Logical stream 1 ended

When I do the same now with the same file (freshly ripped and encoded), the result is different:

    New logical stream (#1, serial: 79e7f7dd): type opus
    Encoded with libopus 1.3.1, libopusenc 0.2.1
    User comments section follows...
            ...
            R128_ALBUM_GAIN=0
            R128_TRACK_GAIN=0
            ...
    Opus stream 1:
            ...
            Playback gain: -13.0781 dB
            ...
    Logical stream 1 ended

Both `R128_ALBUM_GAIN` and `R128_TRACK_GAIN` are set to 0, but instead, the `Playback gain` stream header is set.

This causes troubles … e.g. when playing such a file with Elisa, the volume changes. The `R128_*_GAIN` headers are currently ignored, but the `Playback gain` value seems to be handled by the backend. With no means of handling this.

`scanner/scanner-tag/rgtag.cpp:314` does set the header value via `static_cast<TagLib::Ogg::Opus::File *>(p.first)->setPacket(0, header);`.

"Is this a bug or a feature?!" – I think one should be able to choose if a `Playback gain` is added, or a `R128_*_GAIN` tag … thanks in advance for clarifiying why this happens and/or was changed, and why one can't choose the way how the tags are added!

Cheers, Tobias

**Comment by l3u** [comment]
Seems like `scanner/scanner-tag/rgtag.cpp:290` (`adjust_gain_data(&gd_opus, opus_correction_db);`) causes the `R128_*_GAIN` values to be `0`. When commenting this out, similar values are before are set. The `Playback gain` value is still set though (was `0` before).

**Comment by jiixyj** [comment]
Thanks for the report!

If I recall correctly, `loudness-scanner` never resulted in an output like this:

```
        R128_TRACK_GAIN=-3354
        R128_ALBUM_GAIN=-3405
        Playback gain: 0 dB
```

Instead, it always wrote "0" in either `R128_TRACK_GAIN` or `R128_ALBUM_GAIN` and wrote the actual gain into the Opus header gain field.

Maybe you used a tool to post-process the files such that the Opus header gain is set to "0" and the `R128_*` fields are adjusted accordingly?

The current behavior (writing into the Opus header gain field) matches what `opusenc` (when transferring `REPLAYGAIN_*` tags from `flac`) and foobar2000 (when scanning) do. This behavior is also consistent with rfc7845 which specifies the `R128_*` fields.

But I agree that this results in bad behavior when files are played back with software that doesn't make use of the `R128_*` tags (and doesn't add the 5dB needed to make them have the same volume as ReplayGain'ed files!). The files will sound very quiet.

So we should probably have a command line flag which toggles between the following tagging schemes:

- R128 into header gain (current default behavior):
  ```
        R128_ALBUM_GAIN=0
        R128_TRACK_GAIN=-864
        Playback gain: -8.94922 dB
  ```

- "ReplayGain compatible" Opus header gain (i.e. R128 + 5dB), resulting in a `R128_*` gain field of exactly "-1280":
  ```
        R128_ALBUM_GAIN=-1280
        R128_TRACK_GAIN=-2144
        Playback gain: -3.94922 dB
  ```

- Opus header gain "0":
  ```
        R128_ALBUM_GAIN=-2291
        R128_TRACK_GAIN=-3155
        Playback gain: 0 dB
  ```

**Comment by l3u** [comment]
Yeah, this would be exactly what I would look for!

**Comment by jiixyj** [comment]
Should be fixed, with `--opus-header-gain 0` you can force the Opus header gain to always be "0" to get this behavior:

```
      R128_ALBUM_GAIN=-2291
      R128_TRACK_GAIN=-3155
      Playback gain: 0 dB
```

There are more options for other use cases as well.

**Comment by l3u** [comment]
Very nice! Thanks a lot for the immediate fix :-)
