### ISSUE TITLE
libinput_gstreamer.so: undefined symbol: gst_init

### ISSUE THREAD

**Issue by avinash** [jiixyj/loudness-scanner#9]
Hi,

I've been trying to build loudness-scanner on Ubuntu 12.04 LTS for a few hours now and I am having some issues:

(1) In scanner/scanner-tag/rgtag.cpp, I had to add #include <iostream>

(2) make install only copies libebur128.so* to /usr/loca/lib and not libinput*.so. I had to copy these manually. I also had to copy loudness and loudness-drop-gtk to /usr/local/bin too.

(3) When trying to run loudness, I get the following error:

loudness: symbol lookup error: /usr/local/lib/libinput_gstreamer.so: undefined symbol: gst_init

I have checked a few online resources and this happens when trying to compile a file using this:

g++ a_file.c \`pkg-config --cflags --libs gstreamer-0.10\` -o a_file

instead of:

g++ \`pkg-config --cflags --libs gstreamer-0.10\` a_file.c -o a_file

(i.e. a_file.c needs to be the first argument)

At this point, I have no idea what to do as I don't know much about cmake.

Any idea of what I should do now?

Thanks.

**Comment by jiixyj** [comment]
I must admit that I haven't really tested the current install logic. I usually run the tool directly from the build directory and that works fine. The GStreamer errors are probably related to the transition from GStreamer 0.10 to 1.0 in Ubuntu. Can you try to disable the build of the GStreamer plugin by running "cmake .. -DDISABLE_GSTREAMER=ON"? The other plugins should hopefully work.

I'll try to spin up a Ubuntu VM and fix the build for modern machines.

**Comment by avinash** [comment]
Thanks.

BTW, gstreamer is still at  version 0.10 on Ubuntu 12.04 LTS. I'll try
without the gstreamer plugin and will report.

Avinash

**Comment by avinash** [comment]
I have checked. Everything works when compiled with DISABLE_GSTREAMER. I can scan both MP3 and M4A (AAC) files. Thanks for the tip. It would be nice if the cmake build could work with gstreamer though :-)
